name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0




flutter:

  
  uses-material-design: true

  assets:
   - assets/logo/
   - assets/images/
   - assets/images/category/
   - assets/images/models/
   - assets/svgs/
   - assets/video/

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  